[package]
name = "venus"
version = "0.1.0"
edition = "2024"

[dependencies]
blinds = { version = "0.3.0-alpha0", features = ["event-cache"] }
glam = "0.30.4"
golem = "0.2.0-alpha0"
image = "0.25.6"
platter = "0.2.0-alpha0"

[dev-dependencies]
approx = "0.5.1"
